# Generated by Django 5.2.5 on 2025-11-21 17:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre País')),
                ('codigo_iso', models.CharField(max_length=3, verbose_name='Código ISO (ej: CL, AR, BR)')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'pais',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DivisionAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre División')),
                ('abreviacion', models.CharField(blank=True, max_length=10, null=True, verbose_name='Abreviación')),
                ('codigo_oficial', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Oficial')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisiones', to='proveedores.pais')),
            ],
            options={
                'verbose_name': 'División Administrativa',
                'verbose_name_plural': 'Divisiones Administrativas',
                'db_table': 'division_administrativa',
                'ordering': ['nombre'],
                'unique_together': {('pais', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_nif', models.CharField(max_length=20, unique=True, verbose_name='RUT / NIF')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('nombre_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Fantasía')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('sitio_web', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sitio Web')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=128, null=True, verbose_name='Ciudad')),
                ('condiciones_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('30_DIAS', '30 días'), ('45_DIAS', '45 días'), ('60_DIAS', '60 días'), ('90_DIAS', '90 días')], max_length=50, verbose_name='Condiciones de Pago')),
                ('moneda', models.CharField(choices=[('CLP', 'CLP - Peso Chileno'), ('USD', 'USD - Dólar Estadounidense'), ('EUR', 'EUR - Euro'), ('ARS', 'ARS - Peso Argentino'), ('BRL', 'BRL - Real Brasileño'), ('COP', 'COP - Peso Colombiano'), ('PEN', 'PEN - Sol Peruano'), ('MXN', 'MXN - Peso Mexicano')], max_length=8, verbose_name='Moneda')),
                ('contacto_principal_nombre', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre Contacto')),
                ('contacto_principal_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Contacto')),
                ('contacto_principal_telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono Contacto')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=10, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Registro')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.divisionadministrativa', verbose_name='Región / Estado / Provincia / Depto')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.pais', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='ProveedorProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=6, max_digits=18)),
                ('lead_time_dias', models.PositiveIntegerField(default=7)),
                ('min_lote', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('descuento_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('preferente', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
            options={
                'verbose_name': 'Producto por Proveedor',
                'verbose_name_plural': 'Productos por Proveedor',
                'db_table': 'proveedor_producto',
                'unique_together': {('proveedor', 'producto')},
            },
        ),
    ]
