# Generated by Django 5.2.5 on 2025-11-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='pais',
            field=models.CharField(default='Chile', editable=False, max_length=64),
        ),
    ]
