# Generated by Django 5.2.5 on 2025-11-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_lilis', '0002_remove_usuario_apellidos_remove_usuario_nombres'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='requiere_cambio_password',
            field=models.BooleanField(default=False, verbose_name='Requiere cambio de contraseña'),
        ),
    ]
